name: Test-Inline
version: 2.002
abstract: Inlining your tests next to the code being tested
author: Adam Kennedy<adam@ali.as>
license: unknown
distribution_type: module
build_requires:
  Test::More: 0.47
  Test::ClassAPI: 1.02
requires:
  perl: 5.005
  File::Spec: 0.82
  List::Util: 1.11
  File::Slurp: 9999.04
  File::Find::Rule: 0.26
  Algorithm::Dependency: 1.02
  Class::Autouse: 1.15
  File::Flat: 0.95
  Getopt::Long: 2.34
no_index:
  directory:
    - t.data
    - inc
generated_by: Module::Install version 0.36
